name: Frontend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: List Destinations
      run: |
        cd ~
        find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/| - \1/"
        cd frontend/where2eat
        xcodebuild -scheme "where2eat" -showdestinations
    - name: Run tests
      run: |
        cd frontend/where2eat
        xcodebuild test -scheme where2eat -project where2eat.xcodeproj -destination 'platform=iOS Simulator,name=Any iOS Simulator Device,OS=15.2'
        xcpretty && exit ${PIPESTATUS[0]}

