name: Frontend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: actions/checkout@v1
    - name: List Destinations
      run: |
        cd frontend/where2eat
        xcodebuild -scheme "where2eat" -showdestinations
    - name: Run tests
      run: |
        cd frontend/where2eat
        xcodebuild test -scheme where2eat -project where2eat.xcodeproj -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro'
        xcpretty && exit ${PIPESTATUS[0]}

