name: Frontend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: List Destinations
      run: cd frontend/where2eat && xcodebuild -scheme "where2eat" -showdestinations
    - name: Run tests
      run: cd frontend/where2eat && xcodebuild test -scheme where2eat -project where2eat.xcodeproj -destination 'platform=iOS Simulator,name=Any iOS Simulator Device,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}

