name: Frontend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v1
    - name: List Destinations
      run: |
        find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/| - \1/"
        cd frontend/where2eat
        xcodebuild -scheme "where2eat" -showdestinations
    - name: Run tests
      run: |
        cd frontend/where2eat
        xcodebuild test -scheme where2eat -project where2eat.xcodeproj -destination 'platform=iOS Simulator,id=C6D84733-0788-4941-863C-E8AB7FE0CC23,OS=16.2,name=iPhone 14 Pro'
        xcpretty && exit ${PIPESTATUS[0]}

