# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace TestApp.xcodeproj/project.xcworkspace
          -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
      - name: testing ... iPhone 11
        run: >-
          xcodebuild test -workspace TestApp.xcodeproj/project.xcworkspace
          -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
